Feature/2 step catalog
VoltanBro/ruby-book-store pull request #2
Opened 2020-10-14 17:49 UTC by VoltanBro

Implemented second step:
Catalog;
Show books
Show categories with books count
Filter/Sort books
Paginate books 
Except bestseller logic and images
Book page
Info about book
Price calculator
Read more
Back to results
Without images; Without reviews; Without Add to Cart functionality
Write tests (unit, feature) for your new code.

2020-10-15 07:23 UTC, Volosh1n requested changes
I've made some check of heroku deployment and found some issues:
1) `Get started` button should lead user to `/books`
2) Sorting dropdown does not remember which sorting user had selected. I select any sort, but dropdown always shows "newset first"
3) "Bookstore" in top left corner should move me to homepage.
4) There are "home" button in footer, which does not lead me to homepage, and "shop" button, which does not lead me to `/books`

2020-10-15 07:23 UTC, Volosh1n commented on app/javascript/packs/show_books.js
> +      bookTotalCost.text(unit + total * Math.round(bookPrice.attr("value") * 100) / 100);
`total * Math.round(bookPrice.attr("value") * 100) / 100`
not a big deal, but this thing could be divided on some smaller variables to make it more clean what is going on here. Just to increase ease of understanding

2020-10-15 07:23 UTC, Volosh1n commented on app/javascript/packs/show_books.js
> +
remove extra empty line

2020-10-15 07:23 UTC, Volosh1n commented on app/javascript/packs/show_books.js
> +    let unit = '€'
These variables was above... Not DRY. Can we declare them right after `$(document).on("turbolinks:load",function() {`?

2020-10-15 07:23 UTC, Volosh1n commented on app/queries/sorted_books.rb
> +    create_at: I18n.t('.newest_first'),
create**d**_at?

2020-10-15 07:23 UTC, Volosh1n commented on app/views/books/_book.html.haml
> +- @books.each do |book|
avoid using instance variables in partials.

2020-10-15 07:23 UTC, Volosh1n commented on app/views/books/index.html.haml
> +          %li= link_to t('.newest_first'), books_path(sort_by: :create_at)
create**d**_at

2020-10-15 07:23 UTC, Volosh1n commented on app/views/books/show.html.haml
> +            %input.form-control.quantity-input#book-quantity{ value: 1 }
this input better be disabled, since I can enter here, for example, 0

2020-10-15 07:23 UTC, Volosh1n commented on app/views/categories/books/index.html.haml
> +          %li= link_to t('.newest_first'), category_books_path(sort_by: :create_at)
create**d**_at

2020-10-15 07:23 UTC, Volosh1n commented on app/views/home/_carousel_slide.html.haml
> +- @new_books.each do |book|
avoid using instance variables in partials

2020-10-15 07:23 UTC, Volosh1n commented on app/views/layouts/_header.html.haml
> +            %a{href: "/"}= t('.home')
this should be `link_to`, not `a` tag

2020-10-15 07:23 UTC, Volosh1n commented on app/views/layouts/_header.html.haml
> +                %a.collapse-link{href: "/books"}= t('.all')
`link_to`

2020-10-15 07:23 UTC, Volosh1n commented on app/views/layouts/_header.html.haml
>                  %a.collapse-link{href: "#"}= t('.mobile_development')
`link_to` for all the links

2020-10-15 07:23 UTC, Volosh1n commented on app/views/layouts/_header.html.haml
> +            %a{href: "/"}= t('.home')
`link_to`

2020-10-15 07:23 UTC, Volosh1n commented on app/views/layouts/_header.html.haml
> +                %a{href: "/books"}= t('.all')
`link_to`

2020-10-15 07:23 UTC, Volosh1n commented on app/models/category.rb
> +  validates :title, presence: true, length: { in: CATEGORY_TITLE_RANGE }
let's add validation for title uniqueness.

2020-10-15 07:23 UTC, Volosh1n commented on db/migrate/20201008130917_create_categories.rb
> +      t.string :title, null: false
> let's add validation for title uniqueness.
So, here should be unique index

2020-10-15 07:23 UTC, Volosh1n commented on db/migrate/20201012154702_add_columns_to_book.rb
> +    end
No, do not do such things. We should use `add_column :table_name, :new_column_name, :type` here.

2020-10-15 07:23 UTC, Volosh1n commented on spec/controllers/categories/books_controller_spec.rb
> +require 'rails_helper'
could be removed

2020-10-15 07:23 UTC, Volosh1n commented on spec/controllers/categories/books_controller_spec.rb
> +    before { get :index, params: { category_id: category_id.id } }
`category_id.id` looks a bit strange. change that `let` name to just `category`, since it contains category itself.

2020-10-15 07:23 UTC, Volosh1n commented on spec/factories/book.rb
> +    materials { 'Hardcove, glossy paper' }
`FFaker::Lorem.words.join(', ')`

2020-10-15 07:23 UTC, Volosh1n commented on spec/factories/book.rb
> +    year_of_publication { Random.new.rand(1900..2020) }
`year_of_publication { rand(1900..2020) }` does the same thing

2020-10-15 07:23 UTC, Volosh1n commented on spec/factories/book.rb
>      price { Random.new.rand(9.0..99).ceil(2) }
please, just use rand without Random.new

2020-10-15 07:23 UTC, Volosh1n commented on spec/factories/book.rb
> +    dimensions { 'H: 6.5" x W: 0.9" x D: 5.0' }
let it be something random too

2020-10-15 07:23 UTC, Volosh1n commented on spec/models/category_spec.rb
> +    it {
let's use `do..end` syntax in such cases

2020-10-15 07:23 UTC, Volosh1n commented on spec/rails_helper.rb
> +SimpleCov.minimum_coverage(90)
Let's move it to `spec/support/config/simplecov.rb` and then keep here only `require 'spec/support/config/simplecov'`

2020-10-16 09:12 UTC, Volosh1n requested changes

2020-10-16 09:12 UTC, Volosh1n commented on app/controllers/categories/books_controller.rb
> +      @sort = SortedBooks::SORT_TITLES[params[:sort_by].to_sym] unless params[:sort_by].nil?
SortedBooks -> SortedBooksQuery. please, rename

also, do not use unless if you can just do the same with 'if'.
```ruby
if params[:sort_by].present?
```

2020-10-16 09:12 UTC, Volosh1n commented on db/migrate/20201008130917_create_categories.rb
> +      t.string :title, null: false
@VoltanBro please, fix it too.

2020-10-16 09:12 UTC, Volosh1n commented on db/migrate/20201015085439_add_index_to_categories.rb
> +    add_index :categories, :title, unique: true
do not do such things. I mean, it is the same PR, so you can improve you earlier migration from this PR.

2020-10-16 09:12 UTC, Volosh1n commented on spec/factories/book.rb
> +    dimensions { 'H: 6.5" x W: 0.9" x D: 5.0' }
@VoltanBro Please, do not ignore me..

2020-10-16 09:12 UTC, Volosh1n commented on spec/features/books/books_page_spec.rb
> +    expect(page).to have_css('.badge.general-badge')
what if HTML/CSS changed (redesign, for example), but the page stays?
Please, check Capybara's `have_curernt_path` and `have_content` methods. 
https://devhints.io/capybara

2020-10-16 09:12 UTC, Volosh1n commented on spec/features/books/books_page_spec.rb
> +    expect(page).to have_css('#slider.carousel.slide')
same

2020-10-16 09:12 UTC, Volosh1n commented on spec/features/books/books_page_spec.rb
> +    expect(page).to have_css('#slider.carousel.slide')
same

2020-10-16 09:12 UTC, Volosh1n commented on spec/features/page/home_page_spec.rb
> +    expect(page).to have_css('#slider.carousel.slide')
same

2020-10-16 09:12 UTC, Volosh1n commented on spec/features/page/home_page_spec.rb
> +    expect(page).to have_link('All')
I18n

2020-10-16 11:30 UTC, VoltanBro commented on spec/factories/book.rb
> +    dimensions { 'H: 6.5" x W: 0.9" x D: 5.0' }
@Volosh1n Sorry. It was mistake. I thought that I fixed it

2020-10-16 12:10 UTC, Volosh1n approved these changes

2020-10-16 12:12 UTC, merged